const PAGE_SUFFIX = `Page`;
const DRAWER_SUFFIX = `Drawer`;

export const AppRoutes = {
  PAGES: {
    LandingPage: `Landing${PAGE_SUFFIX}`,
    HomePage: `Home${PAGE_SUFFIX}`,
    BlogsPage: `Blogs${PAGE_SUFFIX}`,
    AboutPage: `About${PAGE_SUFFIX}`,
    WalletPage: `Wallet${PAGE_SUFFIX}`,
    AccountPage: `Account${PAGE_SUFFIX}`,
    ProfilePage: `Profile${PAGE_SUFFIX}`,
    PostingPage: `Posting${PAGE_SUFFIX}`,
    NotificationPage: `Notification${PAGE_SUFFIX}`,
    CommentDetailPage: `CommentDetail${PAGE_SUFFIX}`,
    ReplyDetailPage: `Reply${PAGE_SUFFIX}`,
    BrowserPage: `Browser${PAGE_SUFFIX}`,
    LoginPage: `Login${PAGE_SUFFIX}`,
    SettingsPage: `Settings${PAGE_SUFFIX}`,
    CommunityPage: `Community${PAGE_SUFFIX}`,
    CategoryPage: `Category${PAGE_SUFFIX}`,
    PostingStack: 'PostingStack',
    EditAccountPage: `EditAccount${PAGE_SUFFIX}`,
    ExploreCommunitiesPage: `ExploreCommunities${PAGE_SUFFIX}`,
    ExploreWitnessPage: `ExploreWitness${PAGE_SUFFIX}`,
    VotersPage: `Voters${PAGE_SUFFIX}`,
    DelegationPage: `Delegation${PAGE_SUFFIX}`,
    NewSnippetPage: ` NewSnippet${PAGE_SUFFIX}`,
    ResteemsPage: `Resteems${PAGE_SUFFIX}`,
    AppIntroPage: `AppIntro${PAGE_SUFFIX}`,
    SearchPage: `Search${PAGE_SUFFIX}`,
    FollowersPage: `Followers${PAGE_SUFFIX}`,
    AccountsPage: `Accounts${PAGE_SUFFIX}`,
    PinCodePage: `PinCode${PAGE_SUFFIX}`,
    CommunityReportPage: ` CommunityReport${PAGE_SUFFIX}`,
  },
  DRAWER: {
    HomeDrawer: `Home${DRAWER_SUFFIX}`,
  },
};
