import { AppConstants } from './AppConstants';

export const AppStrings = {
  SDS_BASE: 'https://sds0.steemworld.org',
  IMAGER_SERVER: 'https://steemitimages.com',
  PROMOTION_FOOTER: `<center><sub>Posted using [SteemMobile](${AppConstants.APP_LINK})</sub></center>`,
  RPC_SERVERS: [
    'https://api.steemit.com',
    'https://api.steemyy.com',
    'https://rpc.amarbangla.net',
    'https://steemapi.boylikegirl.club',
    'https://api.steem-fanbase.com',
    'https://api.steemitdev.com',
    'https://api.steem.fans',
  ],
  LANGUAGES: [
    { title: 'Arabic', code: 'ar' },
    { title: 'Bangali', code: 'bn' },
    { title: 'Chinese', code: 'zh-CN' },
    { title: 'English', code: 'en' },
    { title: 'Hindi', code: 'hi' },
    { title: 'Italian', code: 'it' },
    { title: 'Japanese', code: 'ja' },
    { title: 'Korean', code: 'ko' },
    { title: 'Punjabi', code: 'pa' },
    { title: 'Spanish', code: 'es' },
    { title: 'Urdu', code: 'ur' },
  ],
  WEB_APP_URL: 'https://steempro.com',
  CHAIN_ID: '0000000000000000000000000000000000000000000000000000000000000000',
  CHAIN_PREFIX: 'STM',
  CHAIN_TIMEOUT: 5000,
  CURRENT_USER_SCHEMA: 'currentUser',
  POST_DRAFT: 'postDraft',
  COMMENT_DRAFT: 'commentDraft',
  ALL_USERS: 'allUsers',
  STEEM_GLOBALS_SCHEMA: 'steemGlobals',
  SETTINGS_SCHEMA: 'settings',
  ERROR_404:
    'https://steemitimages.com/p/2FFvzA2zeqoVJ2SVhDmmumdPfnVEcahMce9nMwwksSDdRvRCPEvE3VpfDyAgNY97YmmqV9n1UPdBJ3zMh8EJJCTEu2NZLHNTfiTwWREv9xAWNXcLyjpg4iRQDvrop?format=match&mode=fit&width=640',
  GALLERY_SHEET_ID: 'gallerySheet',
  YOUTUBE_VIDEO_SHEET_ID: 'youtubeVideoSheet',
  YOUTUBE_PLAYER_SHEET_ID: 'youtubePlayerSheet',
  IMAGE_SHEET_ID: 'imageSheet',
  LINK_SHEET_ID: 'linkSheet',
  KEY_TYPES: {
    POSTING: 'POSTING',
    ACTIVE: 'ACTIVE',
    OWNER: 'OWNER',
    MASTER: 'MASTER',
    MEMO: 'MEMO',
  },
  FEED_APIS: {
    TRENDING_FEED: { API: 'getActivePostsByTrending', TYPE: 'feed' },
    NEW_FEED: { API: 'getActivePostsByCreated', TYPE: 'feed' },
    HOT_FEED: { API: 'getActivePostsByHot', TYPE: 'feed' },
    PAYOUT_FEED: { API: 'getActivePostsByPayout', TYPE: 'feed' },
    ACCOUNT_FRIENDS_FEED: { API: 'getAccountFriendsFeed', TYPE: 'account' },
    ACCOUNT_POSTS_FEED: { API: 'getPostsByAuthor', TYPE: 'account' },
    ACCOUNT_COMMENTS_FEED: { API: 'getCommentsByAuthor', TYPE: 'feed' },
    ACCOUNT_REPLIES_FEED: { API: 'getCommentsByParentAuthor', TYPE: 'feed' },

    ACCOUNT_COMMUNITIES_FEED: {
      API: 'getAccountCommunitiesFeedByTrending',
      TYPE: 'account',
    },
    PROFILE_BLOGS_FEED: { API: 'getAccountBlog', TYPE: 'profile' },
    PROFILE_POSTS_FEED: { API: 'getPostsByAuthor', TYPE: 'profile' },
  },
};
